"use client";

import React, { memo, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { IconArrowRight, IconPlay } from "./Icons";

type Category = "All" | "Social" | "Title cards" | "Explainers";

interface Piece {
  src: string;
  title: string;
  prompt: string;
  category: Exclude<Category, "All">;
}

// Every piece below is a real composition generated by the agent and served from /public.
const PIECES: Piece[] = [
  {
    src: "/aggressive-zoom-flashcuts.html",
    title: "Flash-cut zoom",
    prompt: "Aggressive zoom punches with white flash cuts on every beat",
    category: "Social",
  },
  {
    src: "/split-screen-attention.html",
    title: "Attention split",
    prompt: "Split screen contrasting focused work against a distracted feed",
    category: "Explainers",
  },
  {
    src: "/host-title-card.html",
    title: "Host title card",
    prompt: "Low-light host intro with a cinematic name card and film grain",
    category: "Title cards",
  },
  {
    src: "/phone-toss-clock.html",
    title: "Phone toss → clock",
    prompt: "Phone gets tossed away, hard cut to a ticking clock",
    category: "Social",
  },
  {
    src: "/neon-host-neuron.html",
    title: "Neon neuron",
    prompt: "Neon host frame that dissolves into firing neurons",
    category: "Explainers",
  },
  {
    src: "/host-intro-text.html",
    title: "Bold text reveal",
    prompt: "Bold kinetic typography reveal for a creator intro",
    category: "Title cards",
  },
];

const CATEGORIES: Category[] = ["All", "Social", "Title cards", "Explainers"];

const BASE_W = 1280;
const BASE_H = 720;

/**
 * Renders a full-viewport composition at 1280×720 and scales it to fit, so pieces
 * authored in px look identical to how they render on export. The iframe only mounts
 * once the card is near the viewport to keep the page light.
 */
function ScaledPreview({ src, title }: { src: string; title: string }) {
  const boxRef = useRef<HTMLDivElement | null>(null);
  const [scale, setScale] = useState(0);
  const [visible, setVisible] = useState(false);
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    const el = boxRef.current;
    if (!el) return;
    const ro = new ResizeObserver(([entry]) => setScale(entry.contentRect.width / BASE_W));
    ro.observe(el);
    const io = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setVisible(true);
          io.disconnect();
        }
      },
      { rootMargin: "200px" }
    );
    io.observe(el);
    return () => {
      ro.disconnect();
      io.disconnect();
    };
  }, []);

  return (
    <div ref={boxRef} className="relative aspect-video w-full overflow-hidden bg-[#0b0b0e]">
      {visible && scale > 0 && (
        <iframe
          src={src}
          title={title}
          loading="lazy"
          sandbox="allow-scripts"
          tabIndex={-1}
          aria-hidden="true"
          onLoad={() => setLoaded(true)}
          className={`absolute left-0 top-0 origin-top-left border-0 pointer-events-none transition-opacity duration-500 ${
            loaded ? "opacity-100" : "opacity-0"
          }`}
          style={{ width: BASE_W, height: BASE_H, transform: `scale(${scale})` }}
        />
      )}
      {!loaded && (
        <div className="absolute inset-0 flex items-center justify-center">
          <span className="w-10 h-10 rounded-full border border-white/15 bg-white/[0.06] flex items-center justify-center text-white/60">
            <IconPlay className="w-4 h-4 fill-current ml-0.5" />
          </span>
        </div>
      )}
    </div>
  );
}

export const ShowcaseGallery = memo(function ShowcaseGallery() {
  const [active, setActive] = useState<Category>("All");
  const pieces = active === "All" ? PIECES : PIECES.filter((p) => p.category === active);

  return (
    <section id="showcase" className="relative w-full py-24 sm:py-28 border-t border-line bg-canvas-subtle scroll-mt-16">
      <div className="container-page">
        <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-6 mb-10">
          <div className="max-w-xl">
            <span className="eyebrow mb-4">Showcase</span>
            <h2 className="text-3xl sm:text-4xl lg:text-5xl font-semibold tracking-[-0.04em] text-fg">
              Made with one prompt.
            </h2>
            <p className="mt-4 text-[15px] sm:text-base text-fg-muted leading-relaxed">
              These are live renders, not screen recordings. Each one started as a single sentence.
            </p>
          </div>

          <div role="tablist" aria-label="Filter showcase" className="flex flex-wrap gap-1.5">
            {CATEGORIES.map((c) => (
              <button
                key={c}
                type="button"
                role="tab"
                aria-selected={active === c}
                onClick={() => setActive(c)}
                className={`h-8 px-3 rounded-full text-[13px] font-medium border transition-colors cursor-pointer ${
                  active === c
                    ? "bg-fg text-canvas border-fg"
                    : "bg-surface text-fg-muted border-line hover:text-fg hover:border-line-strong"
                }`}
              >
                {c}
              </button>
            ))}
          </div>
        </div>

        <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {pieces.map((p) => (
            <li key={p.src} className="card overflow-hidden flex flex-col">
              <ScaledPreview src={p.src} title={p.title} />
              <div className="p-4 flex flex-col gap-2 border-t border-line">
                <div className="flex items-center justify-between gap-3">
                  <h3 className="text-[15px] font-semibold tracking-[-0.015em] text-fg">{p.title}</h3>
                  <span className="badge h-5 px-2 text-[11px] shrink-0">{p.category}</span>
                </div>
                <p className="text-[13px] text-fg-muted leading-relaxed">
                  <span className="font-mono text-fg-subtle mr-1">›</span>
                  {p.prompt}
                </p>
              </div>
            </li>
          ))}
        </ul>

        <div className="mt-10 flex justify-center">
          <Link href="/explore" className="btn btn-secondary">
            Browse all templates
            <IconArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </div>
    </section>
  );
});

export default ShowcaseGallery;
